apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata: # kpt-merge: /example-vlanindex
  name: regional-vlanindex
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|PackageVariant|default|example-vlanindex'
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: vlanindex
    repo: catalog-infra-capi
    workspaceName: main
  downstream:
    package: regional-vlanindex
    repo: edge01
  injectors:
  - kind: WorkloadCluster
    name: regional
  pipeline:
    mutators:
    - image: ghcr.io/kptdev/krm-functions-catalog/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: regional
